services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PLEX_PUID:-1000}
      - PGID=${PLEX_PGID:-1000}
      - TZ=America/Chicago
      - VERSION=docker
    volumes:
      - /mnt/store/plex-config:/config
      - /mnt/store/media:/media
    restart: unless-stopped
