---
ansible_pull_repo_url: https://github.com/emkaytec/foundry
ansible_pull_playbook: ansible/playbook.yml
ansible_pull_checkout_dir: /var/lib/ansible/pull/foundry
ansible_pull_log_file: /var/log/ansible-pull.log
ansible_pull_vault_password_file: /etc/ansible/vault-pass
ansible_pull_config_file: /etc/ansible/ansible.cfg
ansible_pull_wrapper_path: /usr/local/bin/foundry-pull
ansible_pull_service_name: ansible-pull.service
ansible_pull_timer_name: ansible-pull.timer
ansible_pull_apt_lock_timeout: 600
