---
- import_playbook: playbooks/connectivity.yml
- import_playbook: playbooks/apt-mirror.yml
- import_playbook: playbooks/terminfo.yml
- import_playbook: playbooks/tailscale.yml
- import_playbook: playbooks/users.yml
- import_playbook: playbooks/storage.yml
- import_playbook: playbooks/rclone.yml
- import_playbook: playbooks/samba.yml
- import_playbook: playbooks/docker.yml
- import_playbook: playbooks/self-pull.yml
